//! Parakeet TDT Transcription App - Rust Backend
//!
//! Handles audio decoding, model loading, and transcription via parakeet-rs.

pub mod audio;
pub mod commands;

use std::path::PathBuf;
use std::sync::Mutex;

// Re-export commands so main.rs can import them AND so the __cmd__* macros
// generated by #[tauri::command] are visible at the crate root.
pub use commands::{get_last_transcript, init_model, transcribe_audio};

use parakeet_rs::ParakeetTDT;
use serde::{Deserialize, Serialize};

/// Application state holding the model
pub struct AppState {
    /// The Parakeet TDT model
    pub model: Mutex<Option<ParakeetTDT>>,
    /// Model directory path
    pub model_dir: PathBuf,
    /// Last transcription result
    pub last_transcript: Mutex<Option<String>>,
}

/// Transcription result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TranscriptionResult {
    /// The transcribed text
    pub text: String,
    /// Transcription time in seconds
    pub duration_secs: f64,
    /// Whether transcription was successful
    pub success: bool,
    /// Error message if failed
    pub error: Option<String>,
}

/// Create application state
pub fn create_app_state(model_dir: PathBuf) -> AppState {
    AppState {
        model: Mutex::new(None),
        model_dir,
        last_transcript: Mutex::new(None),
    }
}
